name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Run backend tests (Jest)
        run: npm test

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Run frontend tests (Vitest)
        working-directory: frontend
        run: npm test --if-present
