name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Run backend tests (Jest)
        run: npm test

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Run frontend tests (Vitest)
        working-directory: frontend
        run: npm test --if-present

  e2e:
    name: E2E (Playwright)
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install root dependencies
        run: npm ci

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Start backend
        run: |
          nohup node app.js > backend.log 2>&1 &
          echo $! > backend.pid

      - name: Wait for backend
        run: npx wait-on http://127.0.0.1:3001

      - name: Start frontend preview
        working-directory: frontend
        run: |
          nohup npm run preview -- --port 5173 > preview.log 2>&1 &
          echo $! > preview.pid

      - name: Wait for frontend
        run: npx wait-on http://127.0.0.1:5173

      - name: Install Playwright browsers
        working-directory: frontend
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: frontend
        run: npx playwright test --config=playwright.config.ts --reporter=list

      - name: Upload Playwright report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report

  
